# replace "anthos-357623" in the three targets below with your actual project(s)
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: security-demo-pipelne
description: Security-focused CI/CD pipeline on GCP
serialPipeline:
 stages:
 - targetId: test-sec
 - targetId: staging-sec
   profiles:
   - staging
 - targetId: prod-sec
   profiles:
   - prod
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test-sec
description: test cluster
gke:
  cluster: projects/anthos-357623/locations/australia-southeast1-a/clusters/test-sec
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging-sec
description: staging cluster
gke:
  cluster: projects/anthos-357623/locations/australia-southeast1/clusters/staging-sec
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-sec
description: prod GKE cluster
requireApproval: true
gke:
  membership: projects/anthos-357623/locations/australia-southeast1/clusters/prod-sec
